src/ieb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import atividade_registro_view, load_componentes, load_atividades, load_equipes, load_equipes_adicionais,load_indicadores, atividade_registro_detalhe_view, teste_parcerias_view,adicionar_parceria, adicionar_plano,atualizar_situacao_plano, adicionar_produto, adicionar_contrato, atualizar_estado_contrato, adicionar_lei, atualizar_situacao_lei, adicionar_modelo
from . import views 

urlpatterns = [
    path('atividade_registro/', atividade_registro_view, name='atividade_registro'),
    path('ajax/load-componentes/', load_componentes, name='load_componentes'),
    path('ajax/load-atividades/', load_atividades, name='load_atividades'),
    path('ajax/load-equipes/', load_equipes, name='load_equipes'),
    path('ajax/load-equipes-adicionais/', load_equipes_adicionais, name='load_equipes_adicionais'),
    path('load_indicadores/', load_indicadores, name='load_indicadores'),
    path('atividade/<int:pk>/', atividade_registro_detalhe_view, name='atividade_registro_detalhe'),
    path('teste_parcerias/', teste_parcerias_view, name='teste_parcerias'),  # Nova rota para o template de teste
    path('adicionar_parceria/', adicionar_parceria, name='adicionar_parceria'),  # Adicione esta linha
    path('adicionar-plano/', adicionar_plano, name='adicionar_plano'),
    path('atualizar_situacao_plano/', atualizar_situacao_plano, name='atualizar_situacao_plano'),
    path('adicionar_produto/', adicionar_produto, name='adicionar_produto'),
    path('adicionar_contrato/', adicionar_contrato, name='adicionar_contrato'),
    path('atualizar_estado_contrato/', atualizar_estado_contrato, name='atualizar_estado_contrato'),
    path('adicionar_lei/', adicionar_lei, name='adicionar_lei'),
    path('atualizar_situacao_lei/', atualizar_situacao_lei, name='atualizar_situacao_lei'),
    path('adicionar_modelo/', adicionar_modelo, name='adicionar_modelo'),
    path('atividade/<int:pk>/anterior/', views.atividade_registro_anterior, name='atividade_registro_anterior'),
    path('atividade/<int:pk>/proximo/', views.atividade_registro_proximo, name='atividade_registro_proximo'),


]

src/terralab/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2017 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################


"""
# You can register your own urlpatterns here
urlpatterns = [
    url(r'^/?$',
        homepage,
        name='home'),
 ] + urlpatterns
"""
from django.contrib import admin
from django.urls import include, path
from geonode.urls import urlpatterns as geonode_urlpatterns

# Você pode registrar seus próprios urlpatterns aqui
custom_urlpatterns = [
    path('ieb/', include('ieb.urls')),  # Inclua as URLs do seu app 'ieb'
]

# Combine as URLs do GeoNode com as suas URLs personalizadas
urlpatterns = geonode_urlpatterns + custom_urlpatterns

# Ou alternativamente
urlpatterns += custom_urlpatterns

src/ieb/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.gis.db import models as gis_models
from PIL import Image
import os

# Create your models here.
# MOVIMENTO INDÍGENA

class OIsRegional(models.Model):
    ois_reg = models.CharField(max_length=255)
    ois_reg_sigla = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=255)
    nome_repr = models.CharField(max_length=255)
    cargo = models.CharField(max_length=255)

    def __str__(self):
        return self.ois_reg


class OIsLocal(models.Model):
    nome = models.CharField(max_length=255)
    sigla = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=255)
    nome_repr = models.CharField(max_length=255)
    cargo_repr = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class OIRegLoc(models.Model):
    oiregional = models.ForeignKey(OIsRegional, on_delete=models.CASCADE)
    oilocal = models.ForeignKey(OIsLocal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.oiregional.ois_reg} - {self.oilocal.nome}"


class TIs(models.Model):
    nome = models.CharField(max_length=255)
    area = models.FloatField()
    fase = models.CharField(max_length=255)
    etnia = models.CharField(max_length=255)
    municipio = models.CharField(max_length=255)
    uf = models.CharField(max_length=255)
    modalidade = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class Aldeia(models.Model):
    nome = models.CharField(max_length=255)
    tis = models.ForeignKey(TIs, on_delete=models.CASCADE)
    populacao = models.IntegerField()
    ano = models.IntegerField()

    def __str__(self):
        return self.nome


class Indigena(models.Model):
    nome = models.CharField(max_length=255)
    etnia = models.CharField(max_length=255)
    genero = models.CharField(max_length=255)
    cpf = models.CharField(max_length=255)
    rg = models.CharField(max_length=255)
    data_nasc = models.DateField()
    aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    

# MOVIMENTO INDÍGENA - IGATI

class IGATI(models.Model):
    tipo = models.CharField(max_length=255)
    nome = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class TIsIGATI(models.Model):
    igati = models.ForeignKey(IGATI, on_delete=models.CASCADE)
    tis = models.ForeignKey(TIs, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.igati.nome} - {self.tis.nome}"



# GESTÃO DE PROJETOS - FINANCIADORES/INTITUIÇÕES

class Financiador(models.Model):
    nome = models.CharField(max_length=255)
    sigla = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.sigla


class Instituicao(models.Model):
    nome = models.CharField(max_length=255)
    sigla = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class Equipe(models.Model):
    nome = models.CharField(max_length=255)
    cargo = models.CharField(max_length=255)
    cpf = models.CharField(max_length=255)
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nome} - {self.instituicao}"

# GESTÃO DE PROJETOS - PROJETOS/COMPONENTES/ATIVIDADES/EQUIPE

class Projeto(models.Model):
    nome = models.CharField(max_length=255)
    nome_fant = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class Componente(models.Model):
    nome = models.CharField(max_length=255)
    codigo = models.CharField(max_length=255)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    instituicao = models.ForeignKey(Instituicao, on_delete=models.CASCADE)

    def __str__(self):
        return f"Componente {self.codigo}: {self.nome}"


class Atividade(models.Model):
    nome = models.CharField(max_length=255)
    codigo = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)

    def __str__(self):
        return f"Atividade {self.codigo}: {self.nome}"


class EquipeProjeto(models.Model):
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.equipe.nome} - {self.equipe.instituicao}"


class ProjetoOI(models.Model):
    oilocal = models.ForeignKey(OIsLocal, on_delete=models.CASCADE)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.oilocal.nome} - {self.projeto.nome}"


class ProjetoTI(models.Model):
    tis = models.ForeignKey(TIs, on_delete=models.CASCADE)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.tis.nome} - {self.projeto.nome}"


# GESTÃO DE PROJETOS - INDICADORES/METAS/REGISTROS

class Indicador(models.Model):
    nome = models.CharField(max_length=255)
    codigo = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    reporte = models.CharField(max_length=255)

    def __str__(self):
        return self.nome


class Meta(models.Model):
    atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    base = models.FloatField()
    meta = models.FloatField()
    data = models.DateField()

    def __str__(self):
        return f"{self.atividade.codigo} - {self.indicador.nome} - {self.base} - {self.meta}"


class AtividadeRegistro(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    componente = models.ForeignKey(Componente, on_delete=models.CASCADE)
    atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE)
    equipe_projeto = models.ForeignKey(EquipeProjeto, on_delete=models.CASCADE)
    equipe_adicional = models.ManyToManyField(EquipeProjeto, related_name='atividades_registradas', blank=True)
    data_inicio = models.DateField()
    data_final = models.DateField()
    desafios = models.CharField(max_length=255, blank=True)
    propostas = models.CharField(max_length=255, blank=True)
    sucesso = models.CharField(max_length=255, blank=True)
    melhores_praticas = models.CharField(max_length=255, blank=True)
    fotos = models.ImageField(upload_to='fotos/', blank = True)  # Usar ImageField para suportar upload de mídia
    fotos_thumbnail = models.ImageField(upload_to='fotos/thumbnails/', blank=True, editable=False)
    descricao = models.TextField()
    local = models.CharField(max_length=255)
    comentarios = models.TextField(blank=True)
    lista_presenca = models.ImageField(upload_to='listas_presenca/', blank=True)  # Novo campo para lista de presença
    email_organizacao = models.EmailField(max_length=255, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.fotos:
            # Caminho da imagem original
            img_path = self.fotos.path

            # Abrindo a imagem usando Pillow
            with Image.open(img_path) as img:
                # Se a imagem estiver em RGBA, converta para RGB
                if img.mode == 'RGBA':
                    img = img.convert('RGB')

                # Definindo o tamanho máximo da miniatura
                img.thumbnail((300, 300))  # Redimensiona mantendo a proporção

                # Definindo o caminho da miniatura
                thumbnail_dir = os.path.join(os.path.dirname(img_path), 'thumbnails')
                # Verificar se o diretório existe, se não, cria-o
                if not os.path.exists(thumbnail_dir):
                    os.makedirs(thumbnail_dir)

                thumbnail_path = os.path.join(thumbnail_dir, os.path.basename(img_path))

                # Salvando a miniatura no caminho definido
                img.save(thumbnail_path, format='JPEG', quality=85)

                # Atualizando o campo fotos_thumbnail com o caminho da miniatura
                self.fotos_thumbnail.name = os.path.join('fotos/thumbnails/', os.path.basename(img_path))

        super().save(*args, **kwargs)


    def __str__(self):
        return f"{self.data_inicio} - {self.projeto.nome}/COMP-{self.componente.codigo}/ATIV-{self.atividade.codigo} - {self.atividade.nome}"


class AtividadeRegistroEquipe(models.Model):
    equipe_projeto = models.ForeignKey(EquipeProjeto, on_delete=models.CASCADE)
    atividade_registro = models.ForeignKey(AtividadeRegistro, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.equipe_projeto} - {self.atividade_registro}"

# GESTÃO DE PROJETOS - INDICADORES USAID

# 10.2-1 restrito - OK
class AreaRestrito(models.Model):
    atividade_registro = models.ForeignKey(AtividadeRegistro, on_delete=models.CASCADE)
    ti = models.ForeignKey(TIs, on_delete=models.CASCADE, related_name='area_restrito')
    area_em_ha = models.DecimalField(max_digits=12, decimal_places=2)

    class Meta:
        verbose_name = 'Área Restrita'
        verbose_name_plural = 'Áreas Restritas'

    def __str__(self):
        return f"{self.atividade_registro} - {self.ti.nome} - {self.area_em_ha} ha"

# 10.2-2 direto - OK
class AreaDireto(models.Model):
    atividade_registro = models.ForeignKey(AtividadeRegistro, on_delete=models.CASCADE)
    tis = models.ManyToManyField(TIs, related_name='area_direto')
    total_tis = models.PositiveIntegerField(default=0, editable=False)
    total_area = models.FloatField(default=0.0, editable=False)  # Novo campo para armazenar a soma da área das TIs

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        
        # Calcula o total de TIs e a soma da área

src/ieb/forms.py
from django import forms
from .models import AtividadeRegistro, Meta, Indicador, Projeto

class AtividadeRegistroForm(forms.ModelForm):
    indicadores = forms.ModelMultipleChoiceField(
        queryset=Indicador.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    # Adicionando o campo de e-mail da organização
    email_organizacao = forms.EmailField(
        label='E-mail da Organização',
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'Digite o e-mail da organização'})
    )

    class Meta:
        model = AtividadeRegistro
        fields = [
            'projeto', 'componente', 'atividade', 'equipe_projeto',
            'data_inicio', 'data_final', 'desafios', 'propostas',
            'sucesso', 'melhores_praticas', 'fotos', 'equipe_adicional',
            'descricao', 'local', 'comentarios', 'lista_presenca',
            'email_organizacao'
        ]
        widgets = {
            'data_inicio': forms.DateInput(attrs={'type': 'date'}),
            'data_final': forms.DateInput(attrs={'type': 'date'}),
            'equipe_adicional': forms.CheckboxSelectMultiple,
            'desafios': forms.Textarea(attrs={'maxlength': 255}),
            'propostas': forms.Textarea(attrs={'maxlength': 255}),
            'sucesso': forms.Textarea(attrs={'maxlength': 255}),
            'melhores_praticas': forms.Textarea(attrs={'maxlength': 255}),
            'descricao': forms.Textarea(attrs={'maxlength': 255}),
            'comentarios': forms.Textarea(attrs={'maxlength': 255}),
            'local': forms.Textarea(attrs={'maxlength': 255}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['projeto'].required = True
        self.fields['projeto'].queryset = Projeto.objects.all()  # Certifique-se de que há Projetos no banco de dados
        self.fields['projeto'].widget = forms.Select()
        self.fields['componente'].required = True
        self.fields['atividade'].required = True
        self.fields['equipe_projeto'].required = True
        self.fields['data_inicio'].required = True
        self.fields['data_final'].required = True
        self.fields['descricao'].required = True
        self.fields['local'].required = True
        self.fields['fotos'].required = False

        self.fields['descricao'].widget.attrs.update({
        'placeholder': 'Descreva a atividade realizada'
    })
        self.fields['local'].widget.attrs.update({
        'placeholder': 'Indique o local em que a atividade foi realizada. Aldeia - Terra Indígena'
    })
        self.fields['comentarios'].widget.attrs.update({
        'placeholder': 'Comente algo relevante sobre a realização da atividade'
    })
        self.fields['desafios'].widget.attrs.update({
        'placeholder': 'Algum desafio encontrado? Comente aqui...'
    })
        self.fields['propostas'].widget.attrs.update({
        'placeholder': 'Alguma proposta a sugerir? Comente aqui...'
    })
        self.fields['sucesso'].widget.attrs.update({
        'placeholder': 'História de sucesso a compartilhar? Comente aqui...'
    })
        self.fields['melhores_praticas'].widget.attrs.update({
        'placeholder': 'Alguma boa prática a compartilhar? Comente aqui...'
    })

  
  
        if 'atividade' in self.data:
            try:
                atividade_id = int(self.data.get('atividade'))
                self.fields['indicadores'].queryset = Indicador.objects.filter(meta__atividade_id=atividade_id).distinct()
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['indicadores'].queryset = self.instance.atividade.meta_set.all()

    def clean(self):
        cleaned_data = super().clean()
        data_inicio = cleaned_data.get('data_inicio')
        data_final = cleaned_data.get('data_final')

        if data_inicio and data_final:
            if data_inicio > data_final:
                self.add_error('data_final', 'A data final não pode ser anterior à data de início.')

        return cleaned_data

src/ieb/templates/atividade_registro_detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes da Atividade</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'ieb/css/detalhe.css' %}">
    <link rel="stylesheet" href="{% static 'ieb/css/lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'ieb/css/indicadores.css' %}">
</head>
<body>
    <div class="container">
        <h1>Detalhes da Atividade</h1>

        <label>Projeto:</label>
        <div class="field-value">{{ atividade_registro.projeto.nome }}</div>

        <label>Componente:</label>
        <div class="field-value">{{ atividade_registro.componente.nome }}</div>

        <label>Atividade:</label>
        <div class="field-value">{{ atividade_registro.atividade.nome }}</div>

        <label>Equipe Responsável:</label>
        <div class="field-value">{{ atividade_registro.equipe_projeto.equipe.nome }}</div>

        <label>Data Início:</label>
        <div class="field-value">{{ atividade_registro.data_inicio }}</div>

        <label>Data Final:</label>
        <div class="field-value">{{ atividade_registro.data_final }}</div>

        <label>Descrição:</label>
        <div class="field-value">{{ atividade_registro.descricao }}</div>

        <label>Local:</label>
        <div class="field-value">{{ atividade_registro.local }}</div>


        <label>Fotos:</label>
        <div class="field-value">
            {% if atividade_registro.fotos_thumbnail %}
                <img id="thumbnail" src="{{ atividade_registro.fotos_thumbnail.url }}" alt="Fotos Miniatura" style="cursor: pointer;">
            {% elif atividade_registro.fotos %}
                <img id="thumbnail" src="{{ atividade_registro.fotos.url }}" alt="Fotos Original" style="max-width: 300px; height: auto; cursor: pointer;">
            {% else %}
                <p>Nenhuma foto disponível.</p>
            {% endif %}
        </div>

        <!-- Lightbox para visualização ampliada -->
        <div id="lightbox" class="lightbox">
            <span class="close" id="close-lightbox">&times;</span>
            <img id="lightbox-img" src="" alt="Visualização Ampliada">
        </div>

        <label>Lista de Presença:</label>
        <div class="field-value">{{ atividade_registro.lista_presenca }}</div>

        <h2>Indicadores Registrados</h2>

        {% if parcerias %}
            <div class="indicator-section">
                <h3>Parcerias</h3>
                <ul>
                    {% for parceria in parcerias.parcerias.all %}
                        <li>{{ parceria.nome }} - {{ parceria.tipo }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if treinados %}
            <div class="indicator-section">
                <h3>Pessoas Treinadas</h3>
                <p>Total: {{ treinados.total_pessoas }}</p>
                <p>Homens: {{ treinados.homens }}</p>
                <p>Mulheres: {{ treinados.mulheres }}</p>
                <p>Jovens: {{ treinados.jovens }}</p>
                <p>Foco do Treinamento: {{ treinados.get_foco_treinamento_display }}</p>
            </div>
        {% endif %}

        {% if capacitados %}
            <div class="indicator-section">
                <h3>Capacitados</h3>
                <p>Total de Organizações: {{ capacitados.total_organizacoes }}</p>
                <p>Foco da Capacitação: {{ capacitados.get_foco_capacitacao_display }}</p>
                <ul>
                    {% for organizacao in capacitados.organizacoes.all %}
                        <li>{{ organizacao.nome }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if area_restrito %}
            <div class="indicator-section">
                <h3>Área Restrita</h3>
                <p>TI: {{ area_restrito.ti.nome }}</p>
                <p>Área em hectares: {{ area_restrito.area_em_ha }}</p>
            </div>
        {% endif %}

        {% if area_direto %}
            <div class="indicator-section">
                <h3>Área Direto</h3>
                <p>Total de TIs: {{ area_direto.total_tis }}</p>
                <p>Total de Área (ha): {{ area_direto.total_area }}</p>
            </div>
        {% endif %}

        {% if area_geral %}
            <div class="indicator-section">
                <h3>Área Geral</h3>
                <p>Total de TIs: {{ area_geral.total_tis }}</p>
                <p>Total de Área (ha): {{ area_geral.total_area }}</p>
            </div>
        {% endif %}

        {% if produtos %}
            <div class="indicator-section">
                <h3>Produtos</h3>
                <ul>
                    {% for produto in produtos.produtos.all %}
                        <li>{{ produto.nome }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if contratos %}
            <div class="indicator-section">
                <h3>Contratos</h3>
                <ul>
                    {% for contrato in contratos.contratos.all %}
                        <li>{{ contrato.nome }} - {{ contrato.get_estado_display }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if leis %}
            <div class="indicator-section">
                <h3>Leis</h3>
                <ul>
                    {% for lei in leis.leis.all %}
                        <li>{{ lei.nome }} - {{ lei.tipo }} - {{ lei.situacao }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if aplicacao %}
            <div class="indicator-section">
                <h3>Aplicação</h3>
                <p>Total de Pessoas: {{ aplicacao.total_pessoas }}</p>
                <p>Homens: {{ aplicacao.homens }}</p>
                <p>Mulheres: {{ aplicacao.mulheres }}</p>
                <p>Jovens: {{ aplicacao.jovens }}</p>
            </div>
        {% endif %}

        {% if mobilizados %}
            <div class="indicator-section">
                <h3>Mobilizados</h3>
                <p>Valor Mobilizado: {{ mobilizados.valor_mobilizado }}</p>
                <p>Tipo de Apoio: {{ mobilizados.tipo_apoio }}</p>
                <p>Fonte de Apoio: {{ mobilizados.fonte_apoio }}</p>
            </div>
        {% endif %}

        {% if request %}
            <div class="navigation-buttons">
                <a href="{% url 'atividade_registro_anterior' atividade_registro.id %}" class="btn btn-primary">Anterior</a>
                <a href="{% url 'atividade_registro_proximo' atividade_registro.id %}" class="btn btn-secondary">Próximo</a>
            </div>
        {% endif %}
    </div>
    <script src="{% static 'ieb/js/lightbox.js' %}"></script>
</body>
</html>

src/ieb/templates/atividade_registro_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Atividade</title>
    <link rel="stylesheet" href="{% static 'ieb/css/estilo.css' %}">
</head>
<body>
    <div class="container">
        <h1>Formulário de Registro de Atividade</h1>
        
        {% if messages %}
            {% for message in messages %}
                <div class="message {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class='section'>
                <h2>Descrição:</h2>
                <label for="id_projeto">Projeto: <span style="color: red;">*</span></label>
                <select id="id_projeto" name="projeto">
                    <option value="">Selecione um projeto</option>
                    {% for projeto in form.fields.projeto.queryset %}
                        <option value="{{ projeto.id }}">{{ projeto.nome }}</option>
                    {% endfor %}
                </select>
                {{ form.projeto.errors }}

                <label for="id_componente">Componente: <span style="color: red;">*</span></label>
                <select id="id_componente" name="componente">
                    <option value="">Selecione um componente</option>
                </select>
                {{ form.componente.errors }}

                <label for="id_atividade">Atividade: <span style="color: red;">*</span></label>
                <select id="id_atividade" name="atividade">
                    <option value="">Selecione uma atividade</option>
                </select>
                {{ form.atividade.errors }}

                <label for="id_equipe_projeto">Responsável pelo preenchimento: <span style="color: red;">*</span></label>
                <select id="id_equipe_projeto" name="equipe_projeto">
                    <option value="">Selecione uma equipe</option>
                </select>
                {{ form.equipe_projeto.errors }}

                {{ form.data_inicio.errors }}
                <label for="id_data_inicio">Data Início: <span style="color: red;">*</span></label>
                {{ form.data_inicio }}

                {{ form.data_final.errors }}
                <label for="id_data_final">Data Final: <span style="color: red;">*</span></label>
                {{ form.data_final }}

                {{ form.descricao.errors }}
                <label for="id_descricao">Descrição: <span style="color: red;">*</span></label>
                {{ form.descricao }}

                {{ form.local.errors }}
                <label for="id_local">Local: <span style="color: red;">*</span></label>
                {{ form.local }}

                {{ form.fotos.errors }}
                <label for="id_fotos">Fotos: <span style="color: red;">{{ form.fotos.errors }}</span></label>
                {{ form.fotos }}

                {{ form.lista_presenca.errors }}
                <label for="id_lista_presenca">Lista de Presença: <span style="color: red;">{{ form.fotos.errors }}</span></label>
                {{ form.lista_presenca }}
            </div>

            <div class="section">
                <h2>Indicadores</h2>
                <h4>Espaços para preencher valores dos indicadores aparecerão automaticamente, após selecionar a atividade referente ao registro. (Escolha a atividade)</h4>
                <div id="indicadores"></div>
            </div>
     
            <div class='section'>
                
                <label for="id_email_organizacao">Email para notificação: <span style="color: red;">*</span></label>
                <input type="email" id="id_email_organizacao" name="email_organizacao" required>
                {{ form.email_organizacao.errors }}
                
                
            </div>
            <div class="center-button">
                <button type="submit">Salvar</button>
            </div>
        </form>
    </div>

    <div id="url-container"
         data-url-componentes="{% url 'load_componentes' %}"
         data-url-equipes="{% url 'load_equipes' %}"
         data-url-equipes-adicionais="{% url 'load_equipes_adicionais' %}"
         data-url-atividades="{% url 'load_atividades' %}"
         data-url-indicadores="{% url 'load_indicadores' %}"
         data-url-adicionar-parceria="{% url 'adicionar_parceria' %}"
         data-url-atualizar-situacao-plano="{% url 'atualizar_situacao_plano' %}"
         data-url-adicionar-plano="{% url 'adicionar_plano' %}"></div>

    <script>
        const indicadoresConfig = {{ indicadores_config|safe }};
    </script>
    <script src="{% static 'ieb/js/script.js' %}"></script>
    {{ produtos_options|json_script:"produtos-options-data" }}
</body>
</html>